name: 03_Sleep_Action
DEscription: A GitHub Action that sleeps for a specified duration.

runs:
  using: composite
  
  steps:
    - name: Sleep Step 1
      run: echo "Sleeping for 8 seconds..."
      shell: bash

    - name: Sleep Step 2
      run: sleep 8
      shell: bash

    - name: Sleep Step 3
      run: echo "Sleep Action Completed!"
      shell: bash
      
# Added bash shell, because it is required in GitHub Actions composite actions while in act it is optional.
