name: Debug_Messages
run-name: Debug Hello-World Flow
description: "This workflow runs a debug script to print messages in the GitHub Actions log."

on:
  workflow_dispatch:
    
jobs:
  debug_message_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print debug Step 1
        run: echo "Runner Debug Enabled => ${{ runner.debug }}" #RUNNER_DEBUG 

      - name: Print debug Step 2
        run:  |
          echo "::debug::Debug Message Sample."
          echo "::warning::Warning Message Sample."
          echo "::error::Error Message Sample."