name: Workflow_Run_Sequence
description: "This workflow runs after the completion of another workflow. vide 5-0-workflow-sequence.yaml"

on:
  workflow_run:
    workflows: ["Workflow_Sequence"]
    branches: [develop]
    types:
      - completed

jobs:
  sleep_job:
    runs-on: ubuntu-latest
    steps:
      - name: sleep Step 1
        run: sleep 5

      - name: Finish Step 2
        run: echo "The LAST workflow completed!"
