name: If_Condition
run-name: If Condition Flow
description: "This workflow demonstrates the use of if conditions in GitHub Actions."

on:
  workflow_dispatch:

jobs:
  conditional_job:
    runs-on: ubuntu-latest
    steps:   
      - name: Conditional Step 1
        if: github.event_name == 'push'
        run: echo "This step runs only on PUSH events."

      - name: Conditional Step 2
        if: github.event_name == 'workflow_dispatch'
        run: echo "This step runs only on WORKFLOW DISPATCH."

      - name: Conditional Step 3
        if: always()
        run: echo "This step ALWAYS runs, regardless of previous conditions."
    
      - name: Conditional Step 4
        if: failure()
        run: echo "This step runs only if a previous step FAILED."
      
      - name: Conditional Step 5
        if: success()
        run: echo "This step runs only if all previous steps SUCCEEDED."
      
      - name: Conditional Step 6
        if: cancelled()
        run: echo "This step runs only if the workflow was CANCELLED."
      
      - name: Conditional Step 7
        if: github.repository == 'Albejr/github-workflow-learn'
        run: echo "This step runs only if the repository is GITHUB-WORKFLOW-LEARN."

      - name: Conditional Step 8
        if: github.ref_name == 'develop'
        run: echo "This step runs only if the branch is DEVELOP."

      - name: Conditional Step 9
        run: | #GITHUB_REF
          if [ ${{ github.ref }} == 'refs/heads/master' ]; then
            echo "This step runs only if the branch is MASTER."
          elif [ ${{ github.ref }} == 'refs/heads/main' ]; then
            echo "This step runs only if the branch is MAIN."
          else
            echo "This is an unknown branch: ${{ github.ref }}"
          fi

  finalize_job:
    runs-on: ubuntu-latest
    needs: conditional_job
    if: needs.conditional_job.result == 'success'
    steps:
      - name: Conditional Step 1
        run: echo "Finalizing workflow"